org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8
systemProp.file.encoding=UTF-8
project.build.sourceEncoding=UTF-8
project.reporting.outputEncoding=UTF-8
springBootVersion=3.4.13
springDependencyManagementVersion=1.1.7
springCloudVersion=2024.0.3
springCloudAlibabaVersion=2023.0.3.4
